services:
  neo4j:
    container_name: testdb1
    networks:
    - pocnet1
    image: neo4j:5.25.1-community-bullseye
    environment:
      - NEO4J_AUTH=neo4j/R3placeMePlease!
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 5s
  django:
    container_name: gpartition1
    networks:
    - pocnet1
    build: .
    ports:
      - '8000:8000'
    depends_on:
      neo4j:
        condition: service_healthy
    env_file:
      - '.env'

networks:
  pocnet1:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
